#
# Azure DevOps Pipeline for mobile sdk releasing.
#
# Expected pipeline variables (needs to be set for the pipeline in the azure)
#
# REQUIRED VARIABLES 
# ----------------|-------------------
#  repo           | name of the library repository (eg. mtoken-sdk-flutter)
# ----------------|-------------------
#  version        | version of the library to be used (eg. 1.0.0)
# ----------------|-------------------
#  branch         | branch of the library to be used (eg. release/1.0.x)
# ----------------|-------------------
#  type           | type of the library. Currently supported: flutter

name: Mobile Token iOS Build
appendCommitMessageToRunName: false # we dont want to see the commit message in the build name

pool:
  vmImage: 'macos-15'
  # name: 'Default'

variables:
  LIB_FOLDER: ./lib-repo

trigger: none
pr: none

stages:
  - stage: all
    displayName: Main
    jobs:
      - job: release
        displayName: Release
        steps:

        # NAME THE RUN
        - bash: echo "##vso[build.updatebuildnumber]$(REPO)-$(VERSION)"
          displayName: Update azure build number

        # SETUP GIT AND CLONE REPOSITORY
        - bash: |
            git config --local user.email "deployer@wultra.com"
            git config --local user.name "Automatic Deployer"
            git clone --branch $(BRANCH) https://x-access-token:$(GH_TOKEN)@github.com/wultra/$(REPO).git
          displayName: Set git config and clone repository

        # VERIFY THAT THE RELEASE IS PREPARED
        - bash: node ./mobile-release/v1/prepare-release.js -p $(REPO) -v $(VERSION) --verify
          displayName: Verify that the release is prepared

        # CREATE TAG
        - bash: |
            cd $(REPO)
            git tag -a "$(VERSION)" -m "Release $(VERSION)"
            git push origin "$(VERSION)"
          displayName: Create Git tag

        # FLUTTER SECTION
        - bash: brew install flutter
          displayName: Install Flutter
          condition: and(succeeded(), eq(variables['type'], 'flutter'))
        - bash: flutter pub token add https://pub.dev --env-var $(PUB_DEV_TOKEN)
          displayName: Add pub.dev token
          condition: and(succeeded(), eq(variables['type'], 'flutter'))
        - bash: pushd $(REPO) && flutter pub publish --dry-run --force # Remove dry-run to actually publish once tested
          displayName: Publish to pub.dev
          condition: and(succeeded(), eq(variables['type'], 'flutter'))
        # / END OF FLUTTER SECTION

        # FINAL REMINDER
        - bash: echo "Release $(VERSION) of $(REPO) is ready to be used. Don't forget to create GitHub release and publish the documentation to developers.wultra.com!"
          displayName: Final reminder
