name: "Install Cosign"
description: "Action for installing Cosign"

inputs:
  cosign_version:
    description: "Cosign version to install"
    default: 'v3.0.2'

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.0.0
      with:
        cosign-release: ${{ inputs.cosign_version }}
    - name: Check Cosign version
      shell: bash
      run: cosign version