name: "Build Maven project and generate SBOM"
description: "Action for building Maven project and generating SBOM"

inputs:
  module_to_build:
    description: "Module to build"
    required: false
    default: '.'
  project_path:
    description: "Path to module folder"
    required: false
  output_name:
    description: "Name of the output file"
    required: true
  prepare_package:
    description: "Whether to prepare package"
    default: 'true'
  prepare_wars_and_libs:
    description: "Whether to prepare wars and libs"
    default: 'false'
  generate_sbom:
    description: "Whether to generate SBOM"
    default: 'true'

outputs:
  app_version:
    description: Version of the application
    value: ${{ steps.get_version.outputs.app_version }}

runs:
  using: "composite"
  steps:
    - name: Get application version
      shell: bash
      id: get_version
      working-directory: ${{ inputs.project_path != '' && inputs.project_path || '.' }}
      run: |
        if [ "${{ inputs.module_to_build }}" = "." ]; then
          echo "Getting version of whole project in $(pwd)"
          REVISION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        else
          echo "Getting version of module '${{ inputs.module_to_build }}' in $(pwd)"
          REVISION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -pl ${{ inputs.module_to_build }})
        fi
        echo "app_version=$REVISION" >> $GITHUB_OUTPUT

    - name: Prepare package
      shell: bash
      if: ${{ inputs.prepare_package == 'true' }}
      working-directory: ${{ inputs.project_path != '' && inputs.project_path || '.' }}
      run: |
        if [ "${{ inputs.module_to_build }}" = "." ]; then
          echo "Packaging whole project in $(pwd)"
          mvn -U -DuseInternalRepo=true --no-transfer-progress clean package
        else
          echo "Packaging module '${{ inputs.module_to_build }}' in $(pwd)"
          mvn -U -DuseInternalRepo=true --no-transfer-progress clean package -pl ${{ inputs.module_to_build }} -am
        fi

    - name: Prepare wars and libs
      shell: bash
      if: ${{ inputs.prepare_wars_and_libs == 'true'}}
      working-directory: ${{ inputs.project_path != '' && inputs.project_path || '.' }}
      run: |
        if [ "${{ inputs.module_to_build }}" = "." ]; then
          echo "Preparing libs for whole project in $(pwd)"
          mvn -B -U dependency:copy-dependencies -DoutputDirectory=libs --no-transfer-progress
        else
          echo "Preparing libs for module '${{ inputs.module_to_build }}' in $(pwd)"
          mvn -B -U -pl ${{ inputs.module_to_build }} dependency:copy-dependencies -DoutputDirectory=libs --no-transfer-progress
        fi

    - name: Prepare SBOM files
      if: ${{ inputs.generate_sbom == 'true' && inputs.prepare_wars_and_libs == 'true' }}
      shell: bash
      working-directory: ${{ inputs.project_path != '' && inputs.project_path || '.' }}
      run: |
        if [ "${{ inputs.module_to_build }}" = "." ]; then
          SBOM_DIR="./docker/sbom"
        else
          SBOM_DIR="./${{ inputs.module_to_build }}/docker/sbom"
        fi
        
        if [ "${{ inputs.module_to_build }}" = "." ]; then
          LIBS_DIR="./libs"
        else
          LIBS_DIR="./${{ inputs.module_to_build }}/libs"
        fi
        
        mkdir -p "$SBOM_DIR"
        
        find "$LIBS_DIR" -type f \( -name "*.jar" -o -name "*.war" \) | while read FILE; do
          NAME=$(basename "$FILE")
          NAME="${NAME%.*}"
        
          echo "Checking $FILE"
        
          TMP="$SBOM_DIR/$NAME.tmp"
  
          if unzip -p "$FILE" WEB-INF/classes/META-INF/sbom/application.cdx.json > "$TMP" 2>/dev/null; then
            mv "$TMP" "$SBOM_DIR/$NAME.cdx.json"
            echo "SBOM extracted from $FILE"
          elif unzip -p "$FILE" META-INF/sbom/application.cdx.json > "$TMP" 2>/dev/null; then
            mv "$TMP" "$SBOM_DIR/$NAME.cdx.json"
            echo "SBOM extracted from $FILE"
          else
            rm -f "$TMP"
            echo "No SBOM in $FILE"
          fi
        done

    - name: Prepare SBOM file
      if: ${{ inputs.generate_sbom == 'true' && inputs.prepare_wars_and_libs == 'false' }}
      shell: bash
      working-directory: ${{ inputs.project_path != '' && inputs.project_path || '.' }}
      run: |
        if [ "${{ inputs.module_to_build }}" = "." ]; then
          SBOM_DIR="./docker/sbom"
        else
          SBOM_DIR="./${{ inputs.module_to_build }}/docker/sbom"
        fi
        
        NAME='${{ format('{0}-{1}', inputs.output_name != '' && inputs.output_name || inputs.module_to_build, steps.get_version.outputs.app_version) }}'
    
        if [ "${{ inputs.module_to_build }}" = "." ]; then
          TARGET_DIR="./target"
        else
          TARGET_DIR="./${{ inputs.module_to_build }}/target"
        fi
        
        mkdir -p "$SBOM_DIR"
        
        FILE=$(find "$TARGET_DIR" -maxdepth 1 -type f \( -name "${NAME}.war" -o -name "${NAME}.jar" \) | head -n 1)
  
        if [[ -z "$FILE" ]]; then
          echo "No WAR or JAR file found"
          exit 1
        fi
        
        if [[ "$FILE" == *.war ]]; then
          unzip -p "$FILE" WEB-INF/classes/META-INF/sbom/application.cdx.json > ./docker/sbom/${NAME}.cdx.json
        else
          unzip -p "$FILE" META-INF/sbom/application.cdx.json > ./docker/sbom/${NAME}.cdx.json
        fi