on:
  workflow_call:
jobs:
  jar-deploy:
    name: Deploy JAR to GitHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven Package Step to create jar
        run: mvn -B -U  package
      - run: |
          mkdir lib
          cp **/target/*.jar lib 2>/dev/null || :
      - name: Publish JAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Library Artifacts
          path: 'lib/*.jar'
          if-no-files-found: ignore