on:
  workflow_call:
    inputs:
      java_version:
        type: string
        description: set version of java used to run the maven
        default: '17'

jobs:
  jar-deploy:
    name: Deploy JAR to GitHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'
          cache: maven
      - name: Run Maven Package Step to create jar
        run: mvn -B -U  package
      - run: |
          mkdir lib
          cp **/target/*.jar lib 2>/dev/null || :
      - name: Publish JAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Library Artifacts
          path: 'lib/*.jar'
          if-no-files-found: ignore