on:
  workflow_call:
    secrets:
      username:
        required: true
      password:
        required: true
      gpg_passphrase:
        required: false
      gpg_key:
        required: false
    inputs:
      java_version:
        type: string
        description: set version of java used to run the maven
        default: 17
      environment:
        type: string
        description: environment running the deploy maven-publish for using public maven repo and internal-publish for using internal one
        required: true
      release_type:
        type: string
        description: choice of release type (snapshot / release)
        default: snapshot
      directory_path:
        type: string
        description: directory with pom.xml to be executed
        default: .

jobs:
  maven-deploy:
    name: Deploy to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      RELEASE_TYPE: ${{ inputs.release_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Set environment
        # Based on environment and release type of deploy we pick a distribution server - better than setup 3-4 different environments per repository
        run: |
          echo "$ENVIRONMENT:$RELEASE_TYPE"
          if [ "$ENVIRONMENT" == "maven-publish" ]; then
            if [ "$RELEASE_TYPE" == "release" ]; then
              echo "setting server to ossrh-staging-distribution"
              echo "server_id=ossrh-staging-distribution" >> $GITHUB_ENV
            elif [ "$RELEASE_TYPE" == "snapshot" ]; then
              echo "setting server to ossrh-snapshots-distribution"
              echo "server_id=ossrh-snapshots-distribution" >> $GITHUB_ENV
            fi
          elif [ "$ENVIRONMENT" == "internal-publish" ]; then
            echo "setting server to internal"
            echo "server_id=jfrog-central" >> $GITHUB_ENV
          fi
      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java_version }}
          distribution: 'temurin'
          cache: maven
          server-id: ${{ env.server_id }}
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish Libraries to ${{ env.server_id }}
        run: |
          echo "building on $ENVIRONMENT:$RELEASE_TYPE"          
          cd ${{ inputs.directory_path }}
          if [ "$ENVIRONMENT" == "internal-publish" ]; then
            echo "running internal deploy"
            mvn -B -DuseInternalRepo=true --no-transfer-progress deploy 
          elif [ "$ENVIRONMENT" == "maven-publish" ]; then
            echo "running oss deploy"
            if [ "$RELEASE_TYPE" == "release" ]; then
              echo -e "${{ secrets.gpg_key }}" > keyfile.asc
              echo -e "${{ secrets.gpg_passphrase }}" > passphrase.txt
              mvn -B --no-transfer-progress -DperformRelease=true -Dpgp.secretkey=keyfile:keyfile.asc -Dpgp.passphrase=file:passphrase.txt deploy          
            elif [ "$RELEASE_TYPE" == "snapshot" ]; then
              mvn -B --no-transfer-progress deploy
            fi          
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.username }}
          MAVEN_PASSWORD: ${{ secrets.password }}
      - run: |
          mkdir lib
          mkdir war
          cp **/target/*.jar lib 2>/dev/null || :
          cp **/target/*.war war 2>/dev/null || :
      - name: Publish JAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Library Artifacts
          path: 'lib/*.jar'
          if-no-files-found: ignore
      - name: Publish WAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Application Artifacts
          path: 'war/*.war'
          if-no-files-found: ignore

