on:
  workflow_call:
    inputs:
      server-id:
        type: string
        description: server for publishing that should be used, if no specified we are using public maven repository, should be always jfrog-central
        default: jfrog-central
        required: false
      directory_path:
        type: string
        description: directory with pom.xml to be executed
        default: .
#      internal-repo:
#        type: boolean
#        description: should we call the profile with internal repository
#        default: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: SERVER_ID
          server-username: INTERNAL_USERNAME
          server-password: INTERNAL_PASSWORD
          cache: maven
      - name: Run Maven Test Step
        # we are just building and running tests so for master and release branches use public repositories to resolve dependencies, for develop use internal repository.
        # TBD if we should allow overload this by parameter
        run: | 
          echo "$BRANCH"
          cd ${{ inputs.directory_path }}
          # release branches always need published artifact
          if [ "$BRANCH" == "release"* ]; then
            echo "running on public repo"
            mvn -B -U  test             
          else 
            echo "running on internal repo"
            mvn -B -U  test -DuseInternalRepo=true
          fi
        env:
          # those are not environmental secret, but global secret - for readonly access to artifactory
          INTERNAL_USERNAME: ${{ secrets.JFROG_USERNAME }}
          INTERNAL_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          BRANCH: ${{ github.ref_name }}
          SERVER_ID: ${{inputs.server-id}}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          detailed_summary: true
          include_passed: true
          report_paths: '**/target/surefire-reports/*.xml'