on:
  workflow_call:
    inputs:
      directory_path:
        type: string
        description: directory with pom.xml to be executed
        default: .

jobs:
  build:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ${{ inputs.directory_path }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Prepare Build
        run:  mvn -B --no-transfer-progress -DskipTests=true package
      - name: Upload Build Results
        uses: actions/upload-artifact@v3
        with:
          name: build-for-owasp
          path: ${{ inputs.directory_path }}
          retention-days: 1

  test:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: owasp/dependency-check-action:latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-for-owasp
      - run:  mkdir reports
      - name: Run Test
        run: /usr/share/dependency-check/bin/dependency-check.sh --project ${{ github.event.repository.name }} -s . -o reports --format HTML --format JUNIT
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          detailed_summary: true
          include_passed: false
          report_paths: '**/reports/*.xml'
      - name: Upload Report Results
        uses: actions/upload-artifact@v3
        with:
          name: Dependency Check Report
          path: reports


