on:
  workflow_call:
jobs:
  war-deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir war
          cp **/target/*.war war 2>/dev/null || :
      - name: Publish WAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Application Artifacts
          path: 'war/*.war'
          if-no-files-found: ignore