on:
  workflow_call:
    inputs:
      java_version:
        type: string
        description: set version of java used to run the maven
        default: '17'

jobs:
  war-deploy:
    name: Deploy WAR to GitHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'
          cache: maven
      - name: Run Maven Package Step to create war
        run: mvn -B -U  package
      - run: |
          mkdir war
          cp **/target/*.war war 2>/dev/null || :
      - name: Publish WAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Application Artifacts
          path: 'war/*.war'
          if-no-files-found: ignore